layout_spectrum: 0.6272401
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  lightness: 0.1505376
  brandStrength: 1
  brandColors:
    - '#1E1E20'
    - '#6587B4'
    - '#787876'
    - '#E8EBE9'
    - '#283A5E'
  rhythmicContrast: 0.8001714
typography_spectrum: 0.9326460123993456
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: BrianRSchwarz
