favicon: null
name: BrianRSchwarz
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.0625
  brandStrength: 0.25
  rhythmicContrast: 0
  brandColors:
    - '#0c070b'
    - '#37313d'
    - '#5d6665'
    - '#cec7b4'
    - '#9a9c87'
  lightness: 0.5448028
typography_spectrum: 0.92359
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4468803
analytics:
  twitter: null
  google: null
  facebook: null
