name: BrianRSchwarz
favicon: null
layout_spectrum: 0.7534
typography_spectrum: 0.68587
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c070b'
    - '#37313d'
    - '#5d6665'
    - '#cec7b4'
    - '#9a9c87'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
